### ISSUE TITLE
CreatedAt never created if shouldDisableSaveHook to true

### ISSUE THREAD

**Issue by moreaup** [x0bile/happy-mongoose-timestamps#1]
We have to be aware that if we disable save hook, the createdAt will never be updated since mongoose call the save hook when creating an element.
As you can see here : https://mongoosejs.com/docs/middleware.html

Maybe precise it into the documentation.

**Comment by x0bile** [comment]
You are a legend brother, nice find <3

**Comment by moreaup** [comment]
Solve with PR #2
